# Site settings
# These are used to personalize your new site.
title: James Wood # your name here
logo: "/images/Crimson Shoguns - Correct Size[617].png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Science in Computer-Science (class of 2040)
  <br /><br />
  <a href="https://github.com/Kaigan90/Resume">View My Resume</a>
repository: "csci-csu/csci-portfolio"
github_username:  Kaigan90 # update with your username
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal

